---
- name: Install and configure n8n with Docker and Caddy
  hosts: all
  remote_user: root
  gather_facts: true

  tasks:
    - name: Create new non-root user
      user:
        name: dankuta
        group: sudo

    - name: Stop request for passwords from user's sudo commands
      copy:
        content: "dankuta ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/dankuta"
        mode: '0440'
    
    - name: Add SSH Key to new user
      authorized_key:
        user: dankuta
        state: present
        key: "{{ lookup('file', pub_key) }}"

    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl

    - name: Install Docker and Docker Compose
      block:
        - name: Install Docker on Debian-based systems
          apt:
            name: docker.io
            state: present
          when: ansible_os_family == 'Debian'

        - name: Install Docker on RHEL-based systems
          yum:
            name: docker
            state: present
          when: ansible_os_family == 'RedHat'

        - name: Install Docker Compose
          get_url:
            url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system | lower }}-{{ ansible_machine }}"
            dest: /usr/local/bin/docker-compose
            mode: 'ugo+x'
          async: 1200
          poll: 0

      when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

    - name: Clone n8n repository
      git:
        repo: https://github.com/n8n-io/n8n-docker-caddy.git
        dest: /home/dankuta/n8n-docker-caddy
        version: main

    - name: Set ownership of the cloned files
      file:
        path: /home/dankuta/n8n-docker-caddy
        owner: dankuta
        recurse: yes
    
    - name: Add dankuta to the Docker group
      user:
        name: dankuta
        groups: docker
        append: yes
      when: "'docker' in groups"

    - name: Create Docker volumes
      docker_volume:
        name: "{{ item }}"
      loop:
        - caddy_data
        - n8n_data

    - name: Allow traffic on ports 80 and 443
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 80
        - 443

    - name: Update .env file
      replace:
        path: /home/dankuta/n8n-docker-caddy/.env
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - { regexp: 'DATA_FOLDER=/<directory-path>', replace: 'DATA_FOLDER=/home/dankuta' }
        - { regexp: 'DOMAIN_NAME=example.com', replace: 'DOMAIN_NAME=lugarrico.com' }
        - { regexp: 'GENERIC_TIMEZONE=Europe/Berlin', replace: 'GENERIC_TIMEZONE=Africa/Lagos' }

    - name: Update Caddyfile
      replace:
        path: /home/dankuta/n8n-docker-caddy/caddy_config/Caddyfile
        regexp: 'n8n.<domain>.<suffix>'
        replace: 'n8n.lugarrico.com'

    - name: Set ownership for n8n directory
      file:
        path: /home/dankuta/n8n-docker-caddy
        owner: dankuta
        recurse: yes

    - name: Bring up Docker containers
      command: docker-compose up -d
      args:
        chdir: /home/dankuta/n8n-docker-caddy
